name: CI

on:
  push:
  merge_group:

jobs:
  diff-graphql-schema:
    name: Diff GraphQL Schema
    runs-on: ubuntu-latest
    env:
      GRAPHQL_API_ENDPOINT: https://api.otomadb.com/graphql
    steps:
      - uses: actions/checkout@v3
      - uses: kamilkisiela/graphql-inspector@v3.4.0
        with:
          schema: "schema.graphql"
          endpoint: "${{ env.GRAPHQL_API_ENDPOINT }}"

  validate-graphql-queries:
    name: Validate GraphQL Queries
    runs-on: ubuntu-latest
    needs:
      - diff-graphql-schema
    env:
      GRAPHQL_API_ENDPOINT: https://api.otomadb.com/graphql
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install
      - run: pnpm run schema:validate --output ./.inspector-validate-report.json

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install

      - run: pnpm run lint:prettier

      - run: pnpm run lint:eslint --format json --output-file .eslint-report.json
      - name: Annotate ESLint results
        uses: ataylorme/eslint-annotate-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: ".eslint-report.json"

  typecheck:
    runs-on: ubuntu-latest
    needs:
      - diff-graphql-schema
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install
      - run: pnpm run codegen
      - run: pnpm run typecheck
#  storybook:
#    name: Storybook
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: pnpm/action-setup@v2
#        with:
#          version: 7
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 18
#          cache: pnpm
#      - run: pnpm install
#      - run: pnpm run codegen
#      - run: pnpm run storybook:build
